# Generated by Django 2.0.5 on 2018-12-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0002_lau1stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lau1stats',
            name='medium_salary',
        ),
    ]
