# Generated by Django 2.0.5 on 2018-12-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0003_remove_lau1stats_medium_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lau1stats',
            name='lau1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cigeo.Lau1'),
        ),
        migrations.AlterField(
            model_name='nuts3stats',
            name='nuts3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cigeo.Nuts3'),
        ),
    ]
