# Generated by Django 2.0.5 on 2019-01-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0004_auto_20181219_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lau1stats',
            options={'verbose_name': 'Okres', 'verbose_name_plural': 'Okresy'},
        ),
        migrations.AlterModelOptions(
            name='nuts3stats',
            options={'verbose_name': 'Kraj', 'verbose_name_plural': 'Kraje'},
        ),
        migrations.AlterField(
            model_name='lau1stats',
            name='lau1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cigeo.Lau1', verbose_name='Okres'),
        ),
        migrations.AlterField(
            model_name='nuts3stats',
            name='nuts3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cigeo.Nuts3', verbose_name='Kraj'),
        ),
    ]
