# Generated by Django 2.2.3 on 2019-09-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0005_auto_20190119_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lau1stats',
            name='year',
            field=models.IntegerField(default=2007),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nuts3stats',
            name='year',
            field=models.IntegerField(default=2007),
            preserve_default=False,
        ),
    ]
