# Generated by Django 2.2.3 on 2019-09-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0006_socekon_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuts3stats',
            name='nuts3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cigeo.Nuts3', verbose_name='Kraj'),
        ),
    ]
