# Generated by Django 2.2.3 on 2019-09-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0007_socekon_nuts3_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lau1stats',
            name='lau1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cigeo.Lau1', verbose_name='Okres'),
        ),
    ]
