# Generated by Django 2.2.3 on 2020-02-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cigeo', '0004_auto_20190119_2045'),
        ('socekon', '0008_socekon_lau1_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('czk_euro', models.FloatField()),
                ('czk_usd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HumanResourcesNuts3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wages', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socekon.Date')),
                ('nuts3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigeo.Nuts3')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResourcesLau1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhabitans', models.IntegerField()),
                ('productive_inhabitans', models.IntegerField()),
                ('unepmployed', models.IntegerField()),
                ('vacancies', models.IntegerField()),
                ('unemployment', models.FloatField()),
                ('applications_per_vacancy', models.FloatField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socekon.Date')),
                ('lau1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cigeo.Lau1')),
            ],
        ),
    ]
