# Generated by Django 2.2.3 on 2020-02-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0009_human_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanresourceslau1',
            old_name='unepmployed',
            new_name='unemployed',
        ),
    ]
