# Generated by Django 2.2.3 on 2020-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socekon', '0010_human_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresourcesnuts3',
            name='applications_per_vacancy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanresourcesnuts3',
            name='inhabitans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanresourcesnuts3',
            name='productive_inhabitans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanresourcesnuts3',
            name='unemployed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanresourcesnuts3',
            name='unemployment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanresourcesnuts3',
            name='vacancies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
