# Generated by Django 2.0.5 on 2018-05-21 15:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('adm', models.IntegerField(help_text='Kód ADM', primary_key=True, serialize=False)),
                ('street', models.CharField(help_text='Ulice', max_length=200)),
                ('house_number', models.CharField(default=None, help_text='Domovní číslo', max_length=20, null=True)),
                ('orientation_number', models.CharField(default=None, help_text='Orientační číslo', max_length=20, null=True)),
                ('zipcode', models.CharField(help_text='PSČ', max_length=200)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Obec', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.City'),
        ),
    ]
