# Generated by Django 3.0.6 on 2020-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['adm']},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['adm', 'street', 'city', 'zipcode', 'coordinates'], name='addresses_a_adm_ac0e8f_idx'),
        ),
    ]
