# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('middle_name', models.CharField(help_text='Middle name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('titles', models.CharField(help_text='Mgr., PhDr., MUDr., Ing., PhD., ...', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(help_text='Director, HR Manager, ...', max_length=20)),
            ],
        ),
    ]
