# Generated by Django 2.0.5 on 2018-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='titles',
            field=models.CharField(blank=True, help_text='Mgr., PhDr., MUDr., Ing., PhD., ...', max_length=20, null=True),
        ),
    ]
