# Generated by Django 2.2.3 on 2019-12-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0003_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacnititul',
            name='regime',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
