# Generated by Django 2.2.3 on 2019-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0007_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacnititul',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
