# Generated by Django 2.2.3 on 2019-12-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0008_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='op',
            name='op',
            field=models.CharField(max_length=32),
        ),
    ]
