# Generated by Django 2.2.3 on 2019-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0009_indicators_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='resource',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Odkaz na zdroj dat'),
        ),
    ]
