# Generated by Django 2.2.3 on 2019-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0011_frequency_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(max_length=16, verbose_name='Měrná jednotka'),
        ),
    ]
