# Generated by Django 2.2.3 on 2019-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0015_unit_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='resource_comments',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Zdroj metodiky / komentáře'),
        ),
    ]
