# Generated by Django 2.2.3 on 2019-12-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0016_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='resource_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Zdroj metodiky / komentáře'),
        ),
    ]
