# Generated by Django 2.2.3 on 2019-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0017_commens_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(max_length=128),
        ),
    ]
