# Generated by Django 2.2.3 on 2019-12-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacni_matice', '0018_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='frequency',
            field=models.CharField(max_length=128, verbose_name='Frekvence'),
        ),
    ]
