# Generated by Django 2.0.5 on 2018-06-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certifikát', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('titles', models.CharField(blank=True, help_text='Mgr., PhDr., MUDr., Ing., PhD., ...', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(help_text='Director, HR Manager, ...', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('titles', models.CharField(blank=True, help_text='Mgr., PhDr., MUDr., Ing., PhD., ...', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(help_text='Director, HR Manager, ...', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sektor', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Název dodavatele', max_length=200)),
                ('join_venture', models.BooleanField(default=False, help_text='Join-venture')),
                ('custom_made', models.BooleanField(default=False, help_text='Zakázková výroba')),
                ('capital', models.BooleanField(default=False, help_text='Zahraniční kapitál')),
                ('turnover', models.IntegerField(help_text='Obrat [€]')),
                ('export', models.FloatField(help_text='Export [%]')),
                ('employes', models.IntegerField(help_text='Počet zaměstnanců')),
                ('established', models.IntegerField(help_text='Rok založení')),
                ('main_activity', models.CharField(help_text='Hlavní činnost', max_length=200)),
                ('certificates', models.ManyToManyField(to='suppliers.Certificate')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.ContactPerson')),
                ('sectors', models.ManyToManyField(to='suppliers.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='contactperson',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Organisation'),
        ),
    ]
