# Generated by Django 2.0.5 on 2019-06-26 14:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, help_text='Name')),
                ('address', models.TextField(blank=True, help_text='Adresa')),
                ('ico', models.TextField(blank=True, help_text='IČO')),
                ('url', models.URLField(blank=True, help_text='URL')),
                ('core_business', models.TextField(blank=True, help_text='Core business')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Bod', srid=4326)),
            ],
            options={
                'db_table': 'domino"."suppliers',
                'managed': False,
            },
        ),
    ]
