# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address'),
        ),
    ]
