# Generated by Django 2.0.5 on 2018-06-19 15:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Ochraná pásma zemědělského fondu',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(help_text='Celková rozloha <code>m<sup>2</sup></code>', verbose_name='Celková rozloha')),
                ('free', models.IntegerField(help_text='Volná plocha <code>m<sup>2</sup></code>', verbose_name='Volná plocha')),
                ('to_be_build', models.IntegerField(help_text='K zástavbě dle ÚP <code>m<sup>2</sup></code>', verbose_name='K zástavbě')),
                ('for_expansion', models.IntegerField(help_text='K expanzi <code>m<sup>2</sup></code>', verbose_name='K expanzi')),
                ('available_from', models.DateField(help_text='K dispozici od', verbose_name='K dispozici od')),
                ('further_development', models.BooleanField(default=False, verbose_name='Možnost další expanze')),
                ('further_development_description', models.TextField(blank=True, verbose_name='Možnost expanze - popis')),
            ],
            options={
                'verbose_name': 'Rozloha plochy',
                'verbose_name_plural': 'Rozloha ploch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Areal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('status', models.TextField(blank=True, verbose_name='Stav areálu')),
                ('terrain_adjustment', models.BooleanField(default=False, verbose_name='Hrubé terénní úpravy')),
                ('slope', models.IntegerField(choices=[(0, 'Rovina'), (10, 'Mírně svažitý'), (45, 'Svah')], help_text='Sklon pozemku', verbose_name='Sklon svahu')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nadpis dokumentu/přílohy', max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, help_text='Popis dokumentu/přílohy', null=True, verbose_name='Popis')),
                ('attachment', models.FileField(help_text='Soubor s dokumentem/přílohou', upload_to='', verbose_name='Příloha')),
            ],
            options={
                'verbose_name': 'Přílohy',
                'verbose_name_plural': 'Přílohy',
            },
        ),
        migrations.CreateModel(
            name='BrownField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Název', max_length=200, verbose_name='Název')),
                ('status', models.IntegerField(choices=[(0, 'Ke schválení'), (1, 'Rozpracováno'), (2, 'Vráceno k dopracování'), (3, 'Schváleno'), (4, 'Publikováno')], verbose_name='Stav')),
                ('publish_agreement', models.BooleanField(verbose_name='Souhlas s publikací')),
                ('contact_details_agreement', models.BooleanField(help_text='Souhlas s poskytnutím kontaktních údajů', verbose_name='Kontaktní údaje')),
                ('national_program', models.BooleanField(help_text="Žadatel o dotaci z 'Národního programu'", verbose_name='Žadatel o dotaci')),
                ('local_type', models.IntegerField(choices=[(0, 'Areál (plocha s budovami)'), (1, 'Objekt (jedna budova)')], verbose_name='Typ lokality')),
                ('location_type', models.IntegerField(choices=[(0, 'Pomezí (na okraji zastavěného území obce)'), (1, 'Intravilán (na kraji zastavěného území obce)'), (2, 'Extravilán (mimo zastavěné území obce)')], verbose_name='Poloha lokality')),
                ('location_characteristics', models.TextField(verbose_name='Stručná charakteristika lokality')),
                ('build_dat', models.DateField(verbose_name='Doba výstavby')),
                ('reconstrution_readyness', models.IntegerField(choices=[(0, 'Lokalita je připravená. Je možná regenerace celé lokality'), (1, 'Lokalita není připravená k procesu regenerace')], verbose_name='Připravenost k rekonstrukci')),
                ('readynes_description', models.TextField(blank=True, verbose_name='Popis připravenosti k regeneraci')),
                ('previous_usage', models.IntegerField(choices=[(0, 'Zemědělství'), (1, 'Občanská vybavenost (kulturní domy, služby, obchod, atd.)'), (2, 'Bydlení'), (3, 'Průmysl')], verbose_name='Předchozí využití')),
                ('previous_usage_description', models.TextField(blank=True, verbose_name='Popis předchozího využití')),
                ('planed_usage', models.IntegerField(choices=[(0, 'Zemědělství'), (1, 'Občanská vybavenost (kulturní domy, služby, obchod, atd.)'), (2, 'Bydlení'), (3, 'Průmysl a podnikání (služby a kanceláře)'), (4, 'Průmsl, monofunkce')], verbose_name='Plánované využití')),
                ('planed_usage_description', models.TextField(blank=True, verbose_name='Popis plánovaného využití')),
                ('upd', models.IntegerField(choices=[(0, 'Zemědělství, výrba'), (1, 'Smíšená zástavba'), (2, 'Smíšená zóna'), (3, 'Plochy smíšené výrobní')], verbose_name='Územě plánovací dokumantace (ÚPD)')),
                ('upd_conflict', models.TextField(blank=True, verbose_name='Možný střet navrhovaného využití s ÚPD')),
                ('upd_note', models.TextField(blank=True, verbose_name='Poznámka k ÚPD')),
                ('local_government_support', models.BooleanField(default=True, verbose_name='Podpora regenerace místní samosprávou')),
                ('local_government_support_description', models.TextField(blank=True, verbose_name='Popis podpory')),
                ('previous_support_type', models.IntegerField(choices=[(0, 'Žádná'), (1, 'Využití dotací'), (2, '...')], default=0, verbose_name='Dřívější podpora z veřejných zdrojů')),
            ],
            options={
                'verbose_name': 'Brownfield',
                'verbose_name_plural': 'Brownfieldy',
            },
        ),
        migrations.CreateModel(
            name='CulturalProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Ochrana památek',
            },
        ),
        migrations.CreateModel(
            name='DrinkingWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('diameter', models.IntegerField(help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Velikost přípojky')),
                ('well', models.IntegerField(help_text='Studna <code>[m<sup>3</sup>]</code>', verbose_name='Studna')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('well_capacity', models.IntegerField(help_text='Kapacita studny <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita studny')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, related_name='areal', to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Pitná voda',
                'verbose_name_plural': 'Pitná voda',
            },
        ),
        migrations.CreateModel(
            name='EcologicalLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Ekologická zátěž',
            },
        ),
        migrations.CreateModel(
            name='EIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'EIA',
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('current', models.IntegerField(help_text='Napětí <code>[kV]</code>', verbose_name='Napětí')),
                ('capacity', models.IntegerField(help_text='Kapacita <code>[kW]</code>', verbose_name='Kapacita')),
                ('areal', models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Elektřina',
                'verbose_name_plural': 'Elektřina',
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('pressure', models.IntegerField(help_text='Tlak <code>[kPa]</code>', verbose_name='Tlak')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('areal', models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Plyn',
                'verbose_name_plural': 'Plyn',
            },
        ),
        migrations.CreateModel(
            name='GeologicalLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Geologické limity',
            },
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('titles', models.CharField(blank=True, help_text='Mgr., PhDr., MUDr., Ing., PhD., ...', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(help_text='Director, HR Manager, ...', max_length=20)),
                ('brownfield', models.OneToOneField(help_text='Brownfield', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField', verbose_name='Brownfield')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Body, linie, polygony', null=True, srid=4326, verbose_name='Geometrie')),
                ('highway_distance', models.FloatField(default=-1)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.Address', verbose_name='Adresa')),
                ('brownfield', models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField')),
            ],
            options={
                'verbose_name': 'Umístění',
                'verbose_name_plural': 'Umístění',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NatureConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Ochrana přírody',
            },
        ),
        migrations.CreateModel(
            name='NetworksBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Ochraná pásma inženýrských sítí',
            },
        ),
        migrations.CreateModel(
            name='NonPotableWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('diameter', models.IntegerField(help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Velikost přípojky')),
                ('well', models.IntegerField(help_text='Studna <code>[m<sup>3</sup>]</code>', verbose_name='Studna')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('well_capacity', models.IntegerField(help_text='Kapacita studny <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita studny')),
                ('areal', models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, related_name='nonpotablewater', to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Užitková voda',
                'verbose_name_plural': 'Užitková voda',
            },
        ),
        migrations.CreateModel(
            name='OtherLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Jiná omezení',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('priv', 'Soukromé'), ('pub', 'Veřejné')], default='priv', max_length=4, verbose_name='Vlastnictví')),
                ('note', models.TextField(blank=True, help_text='Poznámka', null=True, verbose_name='Poznámka')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Vlastnictví',
                'verbose_name_plural': 'Vlastnictví',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nadpis fotografie', max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, help_text='Popis fotografie', null=True, verbose_name='Popis')),
                ('image', models.ImageField(help_text='Soubor s obrázkem', upload_to='', verbose_name='Obrázek')),
                ('brownfield', models.ForeignKey(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField', verbose_name='BrownField')),
            ],
            options={
                'verbose_name': 'Fotografie',
                'verbose_name_plural': 'Fotografie',
            },
        ),
        migrations.CreateModel(
            name='RailRoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('areal', models.OneToOneField(help_text='Plocha', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Železniční vlečka',
            },
        ),
        migrations.CreateModel(
            name='ResearchFieldWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Průzkumné práce',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('areal', models.OneToOneField(help_text='Plocha', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Příjezdová komunikace',
            },
        ),
        migrations.CreateModel(
            name='RoadBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Ochranná pásma komunikací',
            },
        ),
        migrations.CreateModel(
            name='Telecommunications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('areal', models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Telekomunikace',
                'verbose_name_plural': 'Telekomunikace',
            },
        ),
        migrations.CreateModel(
            name='WasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('diameter', models.IntegerField(help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('areal', models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
            },
        ),
        migrations.CreateModel(
            name='WaterConservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.IntegerField(choices=[(0, 'Ano'), (1, 'Ne'), (2, 'Neznámé/Neurčené')], default=1, verbose_name='Vztahuje se na plochu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('areal', models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal')),
            ],
            options={
                'verbose_name': 'Ochrana podzemních a povrchových vod',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='brownfield',
            field=models.ForeignKey(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField', verbose_name='BrownField'),
        ),
        migrations.AddField(
            model_name='areal',
            name='brownfield',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField', verbose_name='Brownfield'),
        ),
        migrations.AddField(
            model_name='area',
            name='areal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal', verbose_name='Areál'),
        ),
        migrations.AddField(
            model_name='agriculturalprotection',
            name='areal',
            field=models.OneToOneField(help_text='Areal', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal'),
        ),
    ]
