# Generated by Django 2.0.5 on 2018-06-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brownfields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='areal',
        ),
        migrations.AddField(
            model_name='location',
            name='brownfield',
            field=models.OneToOneField(default=0, help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='brownfield',
            field=models.ForeignKey(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField', verbose_name='BrownField'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='areal',
            field=models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='areal',
            field=models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal'),
        ),
        migrations.AlterField(
            model_name='nonpotablewater',
            name='areal',
            field=models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, related_name='nonpotablewater', to='brownfields.Areal'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='brownfield',
            field=models.ForeignKey(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.BrownField', verbose_name='BrownField'),
        ),
        migrations.AlterField(
            model_name='telecommunications',
            name='areal',
            field=models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal'),
        ),
        migrations.AlterField(
            model_name='wastewater',
            name='areal',
            field=models.OneToOneField(help_text='BrownField', on_delete=django.db.models.deletion.CASCADE, to='brownfields.Areal'),
        ),
    ]
