# Generated by Django 2.0.5 on 2018-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brownfields', '0002_auto_20180612_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='highway_distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
