# Generated by Django 2.2.3 on 2019-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circular_economy', '0001_circular_economy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
