version: '3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
            - c:\\Users\\ciis\\src\\ciis:/var/ciis
    container_name: "ciis-django"
    env_file:
        - local.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "ciisdb:192.168.161.77"
    expose:
      - 8000
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    volumes:
            - c:\\Users\\ciis\\src\\ciis\\nginx\:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
