version: '3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - ./:/var/ciis
    container_name: "ciis-django"
    env_file:
        - local.env
    ports:
      - "8080:80"
    extra_hosts:
      - "ciisdb:192.168.161.77"
    depends_on:
      - db
