FROM postgres:10
MAINTAINER Mike Dillon <mike@appropriate.io>

ENV PG_MAJOR 10
ENV POSTGIS_MAJOR 2.4

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts \
           postgis\
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./docker/db/initdb-postgis.sh /docker-entrypoint-initdb.d/postgis.sh
COPY ./docker/db/update-postgis.sh /usr/local/bin
