version: '3.7'

services:
  django_service:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
            - c:\\Users\\ciis\\src\\ciis:/var/ciis/
            - c:\\Users\\ciis\\src\\ssl:/usr/local/etc/ssl/
    container_name: "ciis-django"
    env_file:
        - local.env
    ports:
      - "9000:9000"
    extra_hosts:
      - "ciisdb:192.168.161.77"
    expose:
      - 9000

        #geonetwork:
        #  image: geonetwork:postgres
        #  container_name: ciis-geonetwork
        #  ports:
        #     - "8080:8080"
        #  expose:
        #     - 8080
        #  extra_hosts:
        #     - "ciisdb:192.168.161.77"
        #  env_file:
        #     - local.env
        #  volumes:
        #     - geonetwork:/var/lib/geonetwork_data

  nginx:
    build: ./nginx
    volumes:
            - c:\\Users\\ciis\\src\\ciis\\nginx\:/etc/nginx/conf.d
            - c:\\Users\\ciis\\src\\ssl:/usr/local/etc/ssl/
            - c:\\Users\\ciis\\src\\ciis\\static\:/var/static/
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    depends_on:
      - django_service
        #- geonetwork

volumes:
  geonetwork:
