version: '3.7'

services:
  django_ciis:
    #image: ciis_django_service:postgres-ciis
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /home/jachym/src/czechinvest/ciis/
        target: /var/ciis/
    container_name: "django_ciis"
    env_file:
        - local.env
    ports:
      - "9000:9000"
    expose:
      - 9000
    extra_hosts:
      - "ciisdb:192.168.161.77"

        #  geonetwork_ciis:
        #    image: geonetwork:postgres
        #    env_file:
        #        - local.env
        #    container_name: "geonetwork_ciis"
        #    expose: 
        #      - 8080
        #    ports:
        #      - "8080:8080"
        #    extra_hosts:
        #      - "ciisdb:192.168.161.77"
        #    volumes:
        #      - geonetwork_ciis:/var/lib/geonetwork_data

  nginx-local:
    build: ./nginx
    image: ciis_nginx
    volumes:
      - type: bind
        source: /home/jachym/src/czechinvest/ciis/nginx
        target: /etc/nginx/conf.d
      - type: bind
        source: /home/jachym/src/czechinvest/ciis/ssl
        target: /usr/local/etc/ssl/
      - type: bind
        source: /home/jachym/src/czechinvest/ciis/static/
        target: /var/static/
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    depends_on:
      - django_ciis
        #- geonetwork_ciis

        #volumes:
        # ciis_geonetwork
