# Generated by Django 2.2.3 on 2020-01-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VtpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Název')),
                ('url', models.URLField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address')),
                ('services', models.ManyToManyField(to='vtp.Service')),
                ('type', models.ManyToManyField(to='vtp.VtpType')),
            ],
        ),
    ]
