# Generated by Django 2.2.3 on 2020-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=128),
        ),
    ]
