# Generated by Django 2.0.5 on 2018-05-16 19:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_auto_20171211_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lau1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Kód')),
                ('name', models.CharField(max_length=256, verbose_name='Název')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Hranice')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Body, linie, polygony', null=True, srid=4326, verbose_name='Geometrie')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address', verbose_name='Adresa')),
            ],
            options={
                'verbose_name': 'Umístění',
                'verbose_name_plural': 'Umístění',
            },
        ),
        migrations.CreateModel(
            name='Nuts3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Kód')),
                ('name', models.CharField(max_length=256, verbose_name='Název')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Hranice')),
            ],
        ),
    ]
