# Generated by Django 2.0.5 on 2018-06-19 15:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lau1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Kód')),
                ('name', models.CharField(max_length=256, verbose_name='Název')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Hranice')),
            ],
        ),
        migrations.CreateModel(
            name='Nuts3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Kód')),
                ('name', models.CharField(max_length=256, verbose_name='Název')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Hranice')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(help_text='Linie', srid=4326, verbose_name='Geometrie')),
                ('osm_id', models.CharField(max_length=256)),
                ('code', models.IntegerField(blank=True)),
                ('fclass', models.CharField(max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('ref', models.CharField(blank=True, max_length=256)),
                ('oneway', models.BooleanField(default=False)),
                ('maxspeed', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Silnice a dálnice',
            },
        ),
    ]
