# Generated by Django 2.0.5 on 2018-05-15 21:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lau1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Kód')),
                ('name', models.CharField(max_length=256, verbose_name='Název')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Hranice okresů')),
            ],
        ),
    ]
