# Generated by Django 2.0.5 on 2019-01-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cigeo', '0003_airport_publictransportstop_railwaystation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lau1',
            options={'verbose_name': 'Okres', 'verbose_name_plural': 'Okresy'},
        ),
        migrations.AlterModelOptions(
            name='nuts3',
            options={'verbose_name': 'Kraj', 'verbose_name_plural': 'Kraje'},
        ),
    ]
