# Generated by Django 3.1.1 on 2020-12-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigeo', '0004_auto_20190119_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericnote',
            name='activity',
            field=models.CharField(choices=[], max_length=15),
        ),
    ]
