# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Industry name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Název', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Stručný popis')),
                ('description', models.TextField(blank=True, help_text='Popis')),
                ('year', models.IntegerField(help_text='Foundation year')),
                ('url', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('mentors', models.IntegerField(help_text='Number of mentors')),
                ('seets', models.IntegerField(help_text='Maximum number of seets')),
                ('in_incubation', models.IntegerField(help_text='Number of companies in incubation')),
                ('conditions', models.TextField(help_text='Conditions for SUP (industry, stage etc.)')),
                ('price', models.IntegerField(help_text='Seet/Month')),
                ('note', models.TextField(help_text='Just some note')),
                ('online_database', models.BooleanField()),
                ('published', models.BooleanField()),
                ('evaluation', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address')),
                ('contact_person', models.ManyToManyField(to='contacts.ContactPerson')),
            ],
        ),
        migrations.CreateModel(
            name='InfType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('inc', 'Incubator'), ('vtp', 'VTP'), ('coow', 'Co-working'), ('acc', 'Accelerator')], help_text='Typ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organisation name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Services provided', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='cooperation',
            field=models.ManyToManyField(to='infrastructure.Organisation'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='industry',
            field=models.ManyToManyField(to='infrastructure.Industry'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_type',
            field=models.ManyToManyField(to='infrastructure.InfType'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='services',
            field=models.ManyToManyField(to='infrastructure.Service'),
        ),
    ]
