# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20171121_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='online_database',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='published',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='seets',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='short_description',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='description_cz',
            field=models.TextField(default='', help_text='Popis [cz]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='description_en',
            field=models.TextField(blank=True, help_text='Popis [en]'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo', upload_to=''),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='seats',
            field=models.IntegerField(blank=True, default=0, help_text='Maximum number of seets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions for SUP (industry, stage etc.)'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='mentors',
            field=models.IntegerField(blank=True, help_text='Number of mentors'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='price',
            field=models.IntegerField(blank=True, help_text='Seet/Month'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='year',
            field=models.IntegerField(blank=True, help_text='Foundation year'),
        ),
    ]
