# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20171211_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address'),
        ),
    ]
