# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_auto_20171211_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='in_incubation',
            field=models.IntegerField(blank=True, help_text='Number of companies in incubation', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='note',
            field=models.TextField(blank=True, help_text='Just some note', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
