# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_auto_20171211_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='contact_person',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.ContactPerson'),
        ),
    ]
