# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_auto_20171212_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions for SUP (industry, stage etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='mentors',
            field=models.IntegerField(blank=True, help_text='Number of mentors', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='price',
            field=models.IntegerField(blank=True, help_text='Seet/Month', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='seats',
            field=models.IntegerField(blank=True, help_text='Maximum number of seets', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='year',
            field=models.IntegerField(blank=True, help_text='Foundation year', null=True),
        ),
    ]
