# Generated by Django 3.1.1 on 2020-09-25 16:39

import databazeci.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_databazeci'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_area', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('voicephone', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upto', models.IntegerField()),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Nace',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nace', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=256)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databazeci.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upto', models.IntegerField()),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ico', models.CharField(max_length=24)),
                ('url', models.URLField()),
                ('note', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('technology_readiness', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True, validators=[databazeci.models.is_year], verbose_name='Year of foundation')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.address')),
                ('business_area', models.ManyToManyField(blank=True, to='databazeci.BusinessArea')),
                ('contact', models.ManyToManyField(to='databazeci.Contact')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.department')),
                ('domain', models.ManyToManyField(blank=True, to='databazeci.Domain')),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='databazeci.employees')),
                ('ket', models.ManyToManyField(blank=True, to='databazeci.Ket')),
                ('keywords', models.ManyToManyField(blank=True, to='databazeci.Keyword')),
                ('nace', models.ManyToManyField(blank=True, to='databazeci.Nace')),
                ('subdomain', models.ManyToManyField(blank=True, to='databazeci.Subdomain')),
                ('turnover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='databazeci.turnover')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=256)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.sector')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ManyToManyField(to='databazeci.Department'),
        ),
    ]
