# Generated by Django 3.0.6 on 2020-09-17 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_databazeci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('voicephone', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upto', models.IntegerField()),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Nace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nace', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upto', models.IntegerField()),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ico', models.CharField(max_length=24)),
                ('url', models.URLField()),
                ('note', models.TextField(blank=True)),
                ('profile', models.TextField(blank=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addresses.Address')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='databazeci.Contact')),
                ('department', models.ManyToManyField(to='databazeci.Department')),
                ('domain', models.ManyToManyField(to='databazeci.Domain')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.Employees')),
                ('ket', models.ManyToManyField(to='databazeci.Ket')),
                ('keywords', models.ManyToManyField(to='databazeci.Keyword')),
                ('module', models.ManyToManyField(to='databazeci.Module')),
                ('nace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.Nace')),
                ('subsector', models.ManyToManyField(to='databazeci.Subsector')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.Turnover')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.Sector'),
        ),
    ]
