# Generated by Django 3.0.6 on 2020-09-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0001_databazeci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=256)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databazeci.Domain')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subsector',
        ),
        migrations.DeleteModel(
            name='Subsector',
        ),
        migrations.AddField(
            model_name='subject',
            name='subdomain',
            field=models.ManyToManyField(to='databazeci.Subdomain'),
        ),
    ]
