# Generated by Django 3.1.1 on 2020-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0001_databazeci_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SectorModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=256)),
                ('unid', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sector',
            name='sector',
        ),
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sector',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='sector',
            name='short_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sector',
            name='sort',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='sector',
            name='unid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='product_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='voicephone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='sectormodule',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databazeci.sector'),
        ),
        migrations.AddField(
            model_name='subject',
            name='legal_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='databazeci.legalform'),
        ),
        migrations.AddField(
            model_name='subject',
            name='module',
            field=models.ManyToManyField(to='databazeci.SectorModule'),
        ),
    ]
