# Generated by Django 3.0.6 on 2020-09-24 12:53

import databazeci.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_area', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='module',
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ManyToManyField(to='databazeci.Department'),
        ),
        migrations.AddField(
            model_name='nace',
            name='nace_id',
            field=models.TextField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='technology_rediness',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True, validators=[databazeci.models.is_year], verbose_name='Year of foundation'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='databazeci.Employees'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='nace',
        ),
        migrations.AddField(
            model_name='subject',
            name='nace',
            field=models.ManyToManyField(to='databazeci.Nace'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='turnover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='databazeci.Turnover'),
        ),
        migrations.AddField(
            model_name='subject',
            name='business_area',
            field=models.ManyToManyField(to='databazeci.BusinessArea'),
        ),
    ]
