# Generated by Django 3.1.1 on 2020-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0003_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='databazeci.SectorModule'),
        ),
    ]
