# Generated by Django 3.1.1 on 2020-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0005_certificate_departmans'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
