# Generated by Django 3.0.6 on 2020-09-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0005_more_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='technology_rediness',
            new_name='technology_readiness',
        ),
    ]
