# Generated by Django 3.1.1 on 2020-12-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0006_cedepartmans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='databazeci.Certificate'),
        ),
    ]
