# Generated by Django 3.0.6 on 2020-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0006_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nace',
            name='nace_id',
            field=models.CharField(max_length=16),
        ),
    ]
