# Generated by Django 3.0.6 on 2020-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0007_typo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nace',
            name='id',
        ),
        migrations.AlterField(
            model_name='nace',
            name='nace_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
