# Generated by Django 3.0.6 on 2020-09-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databazeci', '0008_nace_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nace',
            old_name='nace_id',
            new_name='id',
        ),
    ]
