# Generated by Django 2.0.5 on 2019-01-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('middle_name', models.CharField(help_text='Last name', max_length=20)),
                ('role', models.CharField(help_text='Director, HR Manager, ...', max_length=20)),
                ('crm', models.URLField(help_text='CRM link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_en', models.CharField(blank=True, max_length=256)),
                ('legal_form', models.CharField(choices=[('POO', 'Právnická osoba zapsaná v obchodním rejstříku'), ('VVS', 'Veřejná nebo státní vysoká škola'), ('VVI', 'Veřejná výzkumná instituce'), ('ZSP', 'Zájmové sdružení právnických osob, občanské sdružení, spolek')], max_length=8)),
                ('ico', models.IntegerField()),
                ('url', models.URLField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WhoIsWho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=256)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whoiswho.ContactPerson')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoiswho.Institution')),
                ('keywords', models.ManyToManyField(to='whoiswho.Keyword')),
                ('sectors', models.ManyToManyField(to='whoiswho.Sector')),
            ],
        ),
    ]
