# Generated by Django 2.0.5 on 2019-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=40),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=40),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='middle_name',
            field=models.CharField(help_text='Last name', max_length=40),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='role',
            field=models.CharField(help_text='Director, HR Manager, ...', max_length=40),
        ),
    ]
