# Generated by Django 2.0.5 on 2019-01-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0002_whoiswho_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoiswho',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
