# Generated by Django 2.0.5 on 2019-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0003_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoiswho',
            name='specialization',
            field=models.TextField(),
        ),
    ]
