# Generated by Django 2.0.5 on 2019-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0005_whoiswho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='kw',
            field=models.CharField(max_length=256),
        ),
    ]
