# Generated by Django 2.0.5 on 2019-06-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0008_whoiswho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='crm',
            field=models.URLField(blank=True, help_text='CRM link'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=40),
        ),
    ]
