# Generated by Django 2.0.5 on 2018-05-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cigeo', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nadpis dokumentu/přílohy', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Popis dokumentu/přílohy', null=True)),
                ('image', models.FileField(help_text='Soubor s dokumentem/přílohou', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Klíčové slovo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nadpis fotografie', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Popis fotografie', null=True)),
                ('image', models.ImageField(help_text='Soubor s obrázkem', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Název', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Popis', null=True)),
                ('date_inserted', models.DateField(help_text='Datum vložení')),
                ('area', models.FloatField(help_text='Plocha objektu <code>[m<sup>2</sup>]</code>')),
                ('contact_person', models.ManyToManyField(to='contacts.ContactPerson')),
                ('documents', models.ManyToManyField(blank=True, help_text='Dokumenty a přílohy', to='realties.Attachment')),
                ('keywords', models.ManyToManyField(blank=True, help_text='Klíčová slova', to='realties.Keyword')),
                ('location', models.OneToOneField(blank=True, help_text='Umístnění objektu', null=True, on_delete=django.db.models.deletion.PROTECT, to='cigeo.Location')),
                ('original_usage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realties.OriginalUsage')),
                ('photos', models.ManyToManyField(blank=True, help_text='Obrázky a fotky', to='realties.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realties.RealEstateType'),
        ),
    ]
