# Generated by Django 2.0.5 on 2018-05-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cigeo', '0001_initial'),
        ('realties', '0002_auto_20180510_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='location',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='date_inserted',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='original_usage',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='type',
        ),
        migrations.AddField(
            model_name='realestate',
            name='location',
            field=models.OneToOneField(blank=True, help_text='Umístění', null=True, on_delete=django.db.models.deletion.CASCADE, to='cigeo.Location'),
        ),
    ]
