# Generated by Django 2.0.5 on 2018-05-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realties', '0003_auto_20180510_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('industry', 'Průmysl'), ('storage', 'Sklady'), ('office', 'Kanceláře')], help_text='Určení dle ÚP', max_length=10)),
                ('purpose_note', models.TextField(blank=True, help_text='Poznámka k účelu', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='purpose_note',
        ),
        migrations.AlterField(
            model_name='area',
            name='purpose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realties.Purpose'),
        ),
        migrations.AlterField(
            model_name='building',
            name='ownership',
            field=models.OneToOneField(help_text='Typ vlastnictví', on_delete=django.db.models.deletion.CASCADE, to='realties.Ownership'),
        ),
    ]
