# Generated by Django 2.0.5 on 2018-06-19 15:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Název')),
                ('slope', models.IntegerField(choices=[(0, 'Rovina'), (10, 'Mírně svažitý'), (45, 'Svah')], help_text='Sklon pozemku', verbose_name='Sklon svahu')),
                ('ground_water', models.IntegerField(blank=True, help_text='Hladina spodní vody <code>m</code>', null=True, verbose_name='Spodní voda')),
                ('ecology', models.IntegerField(choices=[(0, 'Ne'), (1, 'Ano'), (2, 'Lze předpokládat'), (3, 'Neznámé')], help_text='Ekologická zátěž', verbose_name='Ekologická zátěž')),
                ('note', models.TextField(blank=True, help_text='Poznámka k terénu', null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Plocha',
                'verbose_name_plural': 'Plochy',
            },
        ),
        migrations.CreateModel(
            name='AreaArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(help_text='Celková rozloha <code>m<sup>2</sup></code>', verbose_name='Celková rozloha')),
                ('free', models.IntegerField(help_text='Volná plocha <code>m<sup>2</sup></code>', verbose_name='Volná plocha')),
                ('to_be_build', models.IntegerField(help_text='K zástavbě dle ÚP <code>m<sup>2</sup></code>', verbose_name='K zástavbě')),
                ('for_expansion', models.IntegerField(help_text='K expanzi <code>m<sup>2</sup></code>', verbose_name='K expanzi')),
                ('available_from', models.DateField(help_text='K dispozici od', verbose_name='K dispozici od')),
                ('further_development', models.BooleanField(default=False, verbose_name='Možnost další expanze')),
                ('further_development_description', models.TextField(blank=True, verbose_name='Možnost expanze - popis')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Area', verbose_name='Plocha')),
            ],
            options={
                'verbose_name': 'Rozloha plochy',
                'verbose_name_plural': 'Rozloha ploch',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AreaPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('kc', 'Kč'), ('eur', 'Eur')], help_text='Měna', max_length=3, verbose_name='Měna')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Area')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Ceny',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nadpis dokumentu/přílohy', max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, help_text='Popis dokumentu/přílohy', null=True, verbose_name='Popis')),
                ('attachment', models.FileField(help_text='Soubor s dokumentem/přílohou', upload_to='', verbose_name='Příloha')),
            ],
            options={
                'verbose_name': 'Přílohy',
                'verbose_name_plural': 'Přílohy',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Název')),
                ('building_type', models.CharField(choices=[('prod', 'Výrobní'), ('admin', 'Administrativní'), ('store', 'Skladová'), ('multi', 'Multifunkční')], help_text='Typ budovy', max_length=5, verbose_name='Typ budovy')),
                ('last_inspection', models.DateField(help_text='Datum poslední kolaudace', verbose_name='Poslední kolaudace')),
                ('date_available', models.DateField(help_text='K dispozici od', verbose_name='K dispozici od')),
                ('technical_state', models.CharField(choices=[('planed', 'Plánovaný projekt'), ('new', 'Novostavba'), ('recons', 'Rekonstruovaná'), ('good', 'Zachovalá'), ('need_rec', 'Nutná rekonstrukce'), ('demol', 'K demolici')], help_text='Technický stav budovy', max_length=10, verbose_name='Technický stav')),
                ('last_usage', models.TextField(help_text='Poslední využití', verbose_name='Poslední využití')),
                ('other_restrictions', models.TextField(help_text='Jiná omezení využití', verbose_name='Jiná omezení')),
                ('security', models.BooleanField(help_text='Bezpečnostní systém', verbose_name='Bezpečnostní systém')),
                ('fire_protection', models.BooleanField(help_text='Protipožární ochrana', verbose_name='Protipožární ochrana')),
                ('heating', models.BooleanField(help_text='Vytápění', verbose_name='Vytápění')),
                ('air_condition', models.BooleanField(help_text='Klimatizace', verbose_name='Klimatizace')),
                ('crane', models.BooleanField(help_text='Jeřáb', verbose_name='Jeřáb')),
                ('reception_desk', models.BooleanField(help_text='Recepce', verbose_name='Recepce')),
                ('parking_garage', models.IntegerField(blank=True, help_text='Parkovací místa v garáži', null=True, verbose_name='Parkovací místa v garáži')),
                ('parking_openair', models.IntegerField(blank=True, help_text='Parkovací místa volně', null=True, verbose_name='Parkovací místa volně')),
                ('personal_lift_number', models.IntegerField(blank=True, help_text='Počet osobních výtahů', null=True, verbose_name='Počet osobních výtahů')),
                ('personal_lift_capacity', models.IntegerField(blank=True, help_text='Kapacita osobních výtahů <code>[kg]</code>', null=True, verbose_name='Kapacita osobních výtahů')),
                ('load_lift_number', models.IntegerField(blank=True, help_text='Počet nákladních výtahů', null=True, verbose_name='Počet nákladních výtahů')),
                ('load_lift_capacity', models.IntegerField(blank=True, help_text='Kapacita nákladních výtahů <code>[kg]</code>', null=True, verbose_name='Kapacita nákladních výtahů')),
                ('menza_capacity', models.IntegerField(blank=True, default=None, help_text='Kapacita jídelny', null=True, verbose_name='Kapacita jídelny')),
                ('notes', models.TextField(blank=True, help_text='Poznámky', null=True, verbose_name='Poznámky')),
                ('area', models.ForeignKey(help_text='Plocha', on_delete=django.db.models.deletion.CASCADE, to='realities.Area', verbose_name='Plocha')),
            ],
            options={
                'verbose_name': 'Budova',
                'verbose_name_plural': 'Budovy',
            },
        ),
        migrations.CreateModel(
            name='BuildingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.IntegerField(default=0, help_text='Plocha pro výrobu <code>m<sup>2</sup></code>', verbose_name='Plocha pro výrobu')),
                ('offices', models.IntegerField(default=0, help_text='Plocha pro kanceláře <code>m<sup>2</sup></code>', verbose_name='Plocha kancláře')),
                ('storage', models.IntegerField(default=0, help_text='Plocha pro sklady <code>m<sup>2</sup></code>', verbose_name='Plocha sklady')),
                ('other', models.IntegerField(default=0, help_text='Plocha pro jiné užití <code>m<sup>2</sup></code>', verbose_name='Plocha pro jiné využité')),
            ],
            options={
                'verbose_name': 'Plocha budovy',
                'verbose_name_plural': 'Plochy budovy',
            },
        ),
        migrations.CreateModel(
            name='BuildingDisposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField(blank=True, help_text='Počet podlaží', null=True, verbose_name='Počet podlaží')),
                ('building_type', models.CharField(blank=True, choices=[('wall', 'Příčky'), ('os', 'Open space')], help_text='Typ dispozice', max_length=5, null=True, verbose_name='Typ dispozice')),
                ('pole_distance', models.FloatField(blank=True, help_text='Rozestup sloupů <code>[m]</code>', null=True, verbose_name='Rozestup sloupů')),
                ('loading_capacity', models.FloatField(blank=True, help_text='Nosnost <code>[kg/m<sup>2</sup>]</code>', null=True, verbose_name='Nosnost')),
                ('width', models.FloatField(blank=True, help_text='Šířka <code>[m]</code>', null=True, verbose_name='Šířka')),
                ('height', models.FloatField(blank=True, help_text='Světlá výška <code>[m]</code>', null=True, verbose_name='Světlá výška')),
                ('length', models.FloatField(blank=True, help_text='Délka <code>[m]</code>', null=True, verbose_name='Délka')),
                ('input_height', models.FloatField(blank=True, help_text='Výška vstupu <code>[m]</code>', null=True, verbose_name='Výška vstupu')),
                ('span_width', models.FloatField(blank=True, help_text='Rozpětí nosné konstrukce <code>[m]</code>', null=True, verbose_name='Rozpětí konstrukce')),
                ('construction_material', models.CharField(blank=True, choices=[('concrete', 'Beton'), ('brick', 'Cihla'), ('steel', 'Ocel'), ('other', 'Jiná')], help_text='Konstruční materiál', max_length=10, null=True, verbose_name='Konstruční materiál')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Building')),
            ],
            options={
                'verbose_name': 'Propozice budovy',
                'verbose_name_plural': 'Propozice budovy',
            },
        ),
        migrations.CreateModel(
            name='BuildingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_minium', models.IntegerField(help_text='Cena za služby minimální', verbose_name='Minimální cena za služby')),
                ('services_maxium', models.IntegerField(help_text='Cena za služby maximální', verbose_name='Maximální cena za služby')),
                ('note', models.TextField(blank=True, help_text='Poznámka', null=True, verbose_name='Poznámka')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Building')),
            ],
            options={
                'verbose_name': 'Cena budovy',
                'verbose_name_plural': 'Ceny bodvy',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=20)),
                ('titles', models.CharField(blank=True, help_text='Mgr., PhDr., MUDr., Ing., PhD., ...', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(help_text='Director, HR Manager, ...', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrinkingWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('diameter', models.IntegerField(help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Velikost přípojky')),
                ('well', models.IntegerField(help_text='Studna <code>[m<sup>3</sup>]</code>', verbose_name='Studna')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('well_capacity', models.IntegerField(help_text='Kapacita studny <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita studny')),
            ],
            options={
                'verbose_name': 'Pitná voda',
                'verbose_name_plural': 'Pitná voda',
            },
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('current', models.IntegerField(help_text='Napětí <code>[kV]</code>', verbose_name='Napětí')),
                ('capacity', models.IntegerField(help_text='Kapacita <code>[kW]</code>', verbose_name='Kapacita')),
            ],
            options={
                'verbose_name': 'Elektřina',
                'verbose_name_plural': 'Elektřina',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(help_text='Číslo podlaží', verbose_name='Podlaží')),
                ('number_of_units', models.IntegerField(blank=True, help_text='Počet jednotek', null=True, verbose_name='Počet jednotek')),
                ('total_area', models.IntegerField(blank=True, help_text='Celková plocha <code>m<sup>2</sup></code>', null=True, verbose_name='Celková plocha')),
                ('smallest_unit', models.IntegerField(blank=True, help_text='Velikost nejmenší jednotky <code>m<sup>2</sup></code>', null=True, verbose_name='Plocha nejmenší jednotky')),
                ('biggest_unit', models.IntegerField(blank=True, help_text='Velikost nevětší jednotky <code>m<sup>2</sup></code>', null=True, verbose_name='Plocha největší jednotky')),
                ('building', models.ForeignKey(help_text='Budova', on_delete=django.db.models.deletion.CASCADE, to='realities.Building', verbose_name='Budova')),
            ],
            options={
                'verbose_name': 'Patro',
                'verbose_name_plural': 'Patra',
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('pressure', models.IntegerField(help_text='Tlak <code>[kPa]</code>', verbose_name='Tlak')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
            ],
            options={
                'verbose_name': 'Plyn',
                'verbose_name_plural': 'Plyn',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Klíčové slovo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Body, linie, polygony', null=True, srid=4326, verbose_name='Geometrie')),
                ('highway_distance', models.FloatField(default=-1, help_text='Vzdálenost k dálnici')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.Address', verbose_name='Adresa')),
            ],
            options={
                'verbose_name': 'Umístění',
                'verbose_name_plural': 'Umístění',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonPotableWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('diameter', models.IntegerField(help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Velikost přípojky')),
                ('well', models.IntegerField(help_text='Studna <code>[m<sup>3</sup>]</code>', verbose_name='Studna')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('well_capacity', models.IntegerField(help_text='Kapacita studny <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita studny')),
            ],
            options={
                'verbose_name': 'Užitková voda',
                'verbose_name_plural': 'Užitková voda',
            },
        ),
        migrations.CreateModel(
            name='OriginalUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('priv', 'Soukromé'), ('pub', 'Veřejné')], default='priv', max_length=4, verbose_name='Vlastnictví')),
                ('note', models.TextField(blank=True, help_text='Poznámka', null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Vlastnictví',
                'verbose_name_plural': 'Vlastnictví',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nadpis fotografie', max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, help_text='Popis fotografie', null=True, verbose_name='Popis')),
                ('image', models.ImageField(help_text='Soubor s obrázkem', upload_to='', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Fotografie',
                'verbose_name_plural': 'Fotografie',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_minimum', models.IntegerField(help_text='Celková minimální', verbose_name='Celková minimální')),
                ('total_maximum', models.IntegerField(help_text='Celková maximální', verbose_name='Celková maximální')),
                ('per_sqm_minium', models.IntegerField(help_text='Za <code>m<sup>2</sup></code> minimální', verbose_name='Za m minimální')),
                ('per_sqm_maxium', models.IntegerField(help_text='Za <code>m<sup>2</sup></code> maximální', verbose_name='Za m maximální')),
                ('note', models.TextField(blank=True, help_text='Poznámka', null=True, verbose_name='Poznámka')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('industry', 'Průmysl'), ('storage', 'Sklady'), ('office', 'Kanceláře')], help_text='Určení dle ÚP', max_length=10, verbose_name='Určení')),
                ('note', models.TextField(blank=True, help_text='Poznámka', null=True, verbose_name='Poznámka')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Area')),
            ],
            options={
                'verbose_name': 'Účel',
                'verbose_name_plural': 'Účely',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Název', max_length=200, verbose_name='Název')),
                ('realestate_type', models.IntegerField(choices=[(0, 'Greenfield/Průmyslová zóna'), (1, 'Průmyslový park'), (2, 'areál'), (3, 'Vědecko-technický park'), (4, 'Kanceláře')], help_text='Typ nemovitosti')),
            ],
            options={
                'verbose_name': 'Nemovitost',
                'verbose_name_plural': 'Nemovitosti',
            },
        ),
        migrations.CreateModel(
            name='Telecommunications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('real_estate', models.OneToOneField(blank=True, help_text='Nemovitost', null=True, on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate')),
            ],
            options={
                'verbose_name': 'Telekomunikace',
                'verbose_name_plural': 'Telekomunikace',
            },
        ),
        migrations.CreateModel(
            name='WasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='vzdálenost k objektu <code>[m]</code>', verbose_name='Vzdálenost')),
                ('note', models.TextField(help_text='Poznámka', verbose_name='Poznámka')),
                ('diameter', models.IntegerField(help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('real_estate', models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate', verbose_name='Nemovitost')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('contactperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.ContactPerson')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agenti',
            },
            bases=('realities.contactperson',),
        ),
        migrations.CreateModel(
            name='AreaOwnership',
            fields=[
                ('ownership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.Ownership')),
            ],
            options={
                'verbose_name': 'Vlastnictví plochy',
                'verbose_name_plural': 'Vlastnictví plochy',
            },
            bases=('realities.ownership',),
        ),
        migrations.CreateModel(
            name='BuildingOwnership',
            fields=[
                ('ownership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.Ownership')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Building')),
            ],
            options={
                'verbose_name': 'Vlastnictví budovy',
                'verbose_name_plural': 'Vlastnictví budovy',
            },
            bases=('realities.ownership',),
        ),
        migrations.CreateModel(
            name='FreeBuildingArea',
            fields=[
                ('buildingarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.BuildingArea')),
            ],
            options={
                'verbose_name': 'Volné plochy budovy',
                'verbose_name_plural': 'Volné plochy budovy',
            },
            bases=('realities.buildingarea',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('contactperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.ContactPerson')),
            ],
            options={
                'verbose_name': 'Vlastník',
                'verbose_name_plural': 'Vlastníci',
            },
            bases=('realities.contactperson',),
        ),
        migrations.CreateModel(
            name='RentalPrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.Price')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.AreaPrice')),
            ],
            options={
                'verbose_name': 'Nájemní cena',
                'verbose_name_plural': 'Nájemní ceny',
            },
            bases=('realities.price',),
        ),
        migrations.CreateModel(
            name='SellingPrice',
            fields=[
                ('price_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.Price')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.AreaPrice')),
            ],
            options={
                'verbose_name': 'Prodejní cena',
                'verbose_name_plural': 'Prodejní ceny',
            },
            bases=('realities.price',),
        ),
        migrations.CreateModel(
            name='TotalBuildingArea',
            fields=[
                ('buildingarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.BuildingArea')),
            ],
            options={
                'verbose_name': 'Celková plocha budovy',
                'verbose_name_plural': 'Celkové plochy budovy',
            },
            bases=('realities.buildingarea',),
        ),
        migrations.CreateModel(
            name='UsedBuildingArea',
            fields=[
                ('buildingarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realities.BuildingArea')),
            ],
            options={
                'verbose_name': 'Využitá plocha budovy',
                'verbose_name_plural': 'Využité plochy budovy',
            },
            bases=('realities.buildingarea',),
        ),
        migrations.AddField(
            model_name='photo',
            name='real_estate',
            field=models.ForeignKey(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate', verbose_name='Nemovitost'),
        ),
        migrations.AddField(
            model_name='nonpotablewater',
            name='real_estate',
            field=models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate'),
        ),
        migrations.AddField(
            model_name='location',
            name='real_estate',
            field=models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate'),
        ),
        migrations.AddField(
            model_name='gas',
            name='real_estate',
            field=models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate'),
        ),
        migrations.AddField(
            model_name='electricity',
            name='real_estate',
            field=models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate'),
        ),
        migrations.AddField(
            model_name='drinkingwater',
            name='real_estate',
            field=models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate', to='realities.RealEstate', verbose_name='Nemovitost'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='real_estate',
            field=models.ForeignKey(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate', verbose_name='Nemovitost'),
        ),
        migrations.AddField(
            model_name='area',
            name='real_estate',
            field=models.OneToOneField(help_text='Nemovitost', on_delete=django.db.models.deletion.CASCADE, to='realities.RealEstate'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='agent',
            field=models.ForeignKey(help_text='Agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='realities.Agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(help_text='Vlastník', null=True, on_delete=django.db.models.deletion.SET_NULL, to='realities.Owner', verbose_name='Vlastník'),
        ),
        migrations.AddField(
            model_name='areaownership',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realities.Area'),
        ),
    ]
