# Generated by Django 2.0.5 on 2018-08-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('entrepreneurial_property', '0002_remove_greenfieldlocation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brownfield',
            name='af_removal_price',
        ),
        migrations.RemoveField(
            model_name='brownfield',
            name='agricultural_fund',
        ),
        migrations.RemoveField(
            model_name='developmentpark',
            name='af_removal_price',
        ),
        migrations.RemoveField(
            model_name='developmentpark',
            name='agricultural_fund',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='air_condition',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='canteen',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='crane',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='fire_protection',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='height',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='load_lift',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='other_equipment',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='parking_place',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='personal_lift',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='reception_desk',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='security',
        ),
        migrations.RemoveField(
            model_name='greenfield',
            name='service_price',
        ),
        migrations.RemoveField(
            model_name='industrialareal',
            name='af_removal_price',
        ),
        migrations.RemoveField(
            model_name='industrialareal',
            name='agricultural_fund',
        ),
        migrations.RemoveField(
            model_name='office',
            name='af_removal_price',
        ),
        migrations.RemoveField(
            model_name='office',
            name='agricultural_fund',
        ),
        migrations.RemoveField(
            model_name='scientificpark',
            name='af_removal_price',
        ),
        migrations.RemoveField(
            model_name='scientificpark',
            name='agricultural_fund',
        ),
        migrations.AddField(
            model_name='brownfield',
            name='access_road',
            field=models.IntegerField(choices=[(0, 'Does not exist'), (1, 'Repair needed'), (2, 'Good shape')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brownfield',
            name='build_area',
            field=models.IntegerField(default=0, help_text='Build area <code>[m<sup>2</sup>]</code>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentpark',
            name='access_road',
            field=models.IntegerField(choices=[(0, 'Does not exist'), (1, 'Repair needed'), (2, 'Good shape')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentpark',
            name='build_area',
            field=models.IntegerField(default=0, help_text='Build area <code>[m<sup>2</sup>]</code>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenfield',
            name='access_road',
            field=models.IntegerField(choices=[(0, 'Does not exist'), (1, 'Repair needed'), (2, 'Good shape')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenfieldlocation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.Address', verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='industrialareal',
            name='access_road',
            field=models.IntegerField(choices=[(0, 'Does not exist'), (1, 'Repair needed'), (2, 'Good shape')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrialareal',
            name='build_area',
            field=models.IntegerField(default=0, help_text='Build area <code>[m<sup>2</sup>]</code>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='access_road',
            field=models.IntegerField(choices=[(0, 'Does not exist'), (1, 'Repair needed'), (2, 'Good shape')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='build_area',
            field=models.IntegerField(default=0, help_text='Build area <code>[m<sup>2</sup>]</code>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificpark',
            name='access_road',
            field=models.IntegerField(choices=[(0, 'Does not exist'), (1, 'Repair needed'), (2, 'Good shape')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificpark',
            name='build_area',
            field=models.IntegerField(default=0, help_text='Build area <code>[m<sup>2</sup>]</code>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brownfield',
            name='ecological_stress',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'presumed')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brownfield',
            name='free_area',
            field=models.IntegerField(help_text='Free area <code>[m<sup>2</sup>]</code>'),
        ),
        migrations.AlterField(
            model_name='brownfield',
            name='previous_usage',
            field=models.CharField(choices=[('service', 'Public services'), ('military', 'Military'), ('agro', 'Agrucultural'), ('industry', 'Industry'), ('mining', 'Mining'), ('living', 'Living'), ('transport', 'Transporatation and logistics'), ('traveling', 'Traveling')], max_length=16),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='crm',
            field=models.URLField(help_text='CRM link'),
        ),
        migrations.AlterField(
            model_name='developmentpark',
            name='ecological_stress',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'presumed')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developmentpark',
            name='free_area',
            field=models.IntegerField(help_text='Free area <code>[m<sup>2</sup>]</code>'),
        ),
        migrations.AlterField(
            model_name='developmentpark',
            name='previous_usage',
            field=models.CharField(choices=[('service', 'Public services'), ('military', 'Military'), ('agro', 'Agrucultural'), ('industry', 'Industry'), ('mining', 'Mining'), ('living', 'Living'), ('transport', 'Transporatation and logistics'), ('traveling', 'Traveling')], max_length=16),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='agricultural_fund',
            field=models.BooleanField(default=0, help_text='Taken out of Agriculture fund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='ecological_stress',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'presumed')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='free_area',
            field=models.IntegerField(help_text='Free area <code>[m<sup>2</sup>]</code>'),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='previous_usage',
            field=models.CharField(choices=[('service', 'Public services'), ('military', 'Military'), ('agro', 'Agrucultural'), ('industry', 'Industry'), ('mining', 'Mining'), ('living', 'Living'), ('transport', 'Transporatation and logistics'), ('traveling', 'Traveling')], max_length=16),
        ),
        migrations.AlterField(
            model_name='greenfielddrinkwater',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Capacity <code>[m<sup>3</sup>/d]</code>', verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='greenfielddrinkwater',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldelectricity',
            name='current',
            field=models.IntegerField(blank=True, help_text='Napětí <code>[kV]</code>', verbose_name='Napětí'),
        ),
        migrations.AlterField(
            model_name='greenfieldelectricity',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldgas',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Capacity <code>[m<sup>3</sup>/d]</code>', verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='greenfieldgas',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldgas',
            name='pressure',
            field=models.IntegerField(blank=True, help_text='Pressure <code>[kPa]</code>', verbose_name='Pressure'),
        ),
        migrations.AlterField(
            model_name='greenfieldtechnologicalwater',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Capacity <code>[m<sup>3</sup>/d]</code>', verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='greenfieldtechnologicalwater',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldtelecommunication',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewaterindustrial',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewaterrain',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewatersevage',
            name='distance',
            field=models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace'),
        ),
        migrations.AlterField(
            model_name='industrialareal',
            name='ecological_stress',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'presumed')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industrialareal',
            name='free_area',
            field=models.IntegerField(help_text='Free area <code>[m<sup>2</sup>]</code>'),
        ),
        migrations.AlterField(
            model_name='industrialareal',
            name='previous_usage',
            field=models.CharField(choices=[('service', 'Public services'), ('military', 'Military'), ('agro', 'Agrucultural'), ('industry', 'Industry'), ('mining', 'Mining'), ('living', 'Living'), ('transport', 'Transporatation and logistics'), ('traveling', 'Traveling')], max_length=16),
        ),
        migrations.AlterField(
            model_name='office',
            name='ecological_stress',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'presumed')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='free_area',
            field=models.IntegerField(help_text='Free area <code>[m<sup>2</sup>]</code>'),
        ),
        migrations.AlterField(
            model_name='office',
            name='previous_usage',
            field=models.CharField(choices=[('service', 'Public services'), ('military', 'Military'), ('agro', 'Agrucultural'), ('industry', 'Industry'), ('mining', 'Mining'), ('living', 'Living'), ('transport', 'Transporatation and logistics'), ('traveling', 'Traveling')], max_length=16),
        ),
        migrations.AlterField(
            model_name='scientificpark',
            name='ecological_stress',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no'), (2, 'presumed')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scientificpark',
            name='free_area',
            field=models.IntegerField(help_text='Free area <code>[m<sup>2</sup>]</code>'),
        ),
        migrations.AlterField(
            model_name='scientificpark',
            name='previous_usage',
            field=models.CharField(choices=[('service', 'Public services'), ('military', 'Military'), ('agro', 'Agrucultural'), ('industry', 'Industry'), ('mining', 'Mining'), ('living', 'Living'), ('transport', 'Transporatation and logistics'), ('traveling', 'Traveling')], max_length=16),
        ),
    ]
