# Generated by Django 2.0.5 on 2018-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0003_auto_20180823_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfieldwastewaterindustrial',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewaterindustrial',
            name='diameter',
            field=models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewaterrain',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewaterrain',
            name='diameter',
            field=models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewatersevage',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky'),
        ),
        migrations.AlterField(
            model_name='greenfieldwastewatersevage',
            name='diameter',
            field=models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr'),
        ),
    ]
