# Generated by Django 2.0.5 on 2018-08-23 15:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('cigeo', '0003_airport_publictransportstop_railwaystation'),
        ('entrepreneurial_property', '0004_auto_20180823_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentParkAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('attachment', models.FileField(help_text='Attachment file', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkDrinkWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('diameter', models.IntegerField(blank=True, help_text='<code>[mm]</code>', null=True, verbose_name='Diameter')),
                ('capacity', models.IntegerField(blank=True, help_text='Capacity <code>[m<sup>3</sup>/d]</code>', verbose_name='Capacity')),
                ('well', models.BooleanField(verbose_name='Well')),
                ('well_capacity', models.IntegerField(blank=True, help_text='Well capacity <code>[m<sup>3</sup>/d]</code>', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkElectricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('current', models.IntegerField(blank=True, help_text='Napětí <code>[kV]</code>', verbose_name='Napětí')),
                ('capacity', models.IntegerField(help_text='Kapacita <code>[MW]</code>', verbose_name='Kapacita')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkGas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('diameter', models.IntegerField(blank=True, help_text='<code>[mm]</code>', null=True, verbose_name='Diameter')),
                ('pressure', models.IntegerField(blank=True, help_text='Pressure <code>[kPa]</code>', verbose_name='Pressure')),
                ('capacity', models.IntegerField(blank=True, help_text='Capacity <code>[m<sup>3</sup>/d]</code>', verbose_name='Capacity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkGenericNote',
            fields=[
                ('genericnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cigeo.GenericNote')),
            ],
            bases=('cigeo.genericnote',),
        ),
        migrations.CreateModel(
            name='DevelopmentParkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Body, linie, polygony', null=True, srid=4326, verbose_name='Geometrie')),
                ('highway_distance', models.FloatField(default=-1)),
                ('airport_distance', models.FloatField(default=-1)),
                ('public_transport_distance', models.FloatField(default=-1)),
                ('railway_distance', models.FloatField(default=-1)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.Address', verbose_name='Adresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('image', models.ImageField(help_text='Image file', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkTechnologicalWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('diameter', models.IntegerField(blank=True, help_text='<code>[mm]</code>', null=True, verbose_name='Diameter')),
                ('capacity', models.IntegerField(blank=True, help_text='Capacity <code>[m<sup>3</sup>/d]</code>', verbose_name='Capacity')),
                ('well', models.BooleanField(verbose_name='Well')),
                ('well_capacity', models.IntegerField(blank=True, help_text='Well capacity <code>[m<sup>3</sup>/d]</code>', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkTelecommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('technology', models.CharField(blank=True, choices=[('optic', 'Optic'), ('metalic', 'Metalic'), ('wifi', 'WIFI'), ('cell', 'Cellular')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkWasteWaterIndustrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkWasteWaterRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkWasteWaterSevage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='developmentpark',
            name='ecological_stress',
        ),
        migrations.AddField(
            model_name='brownfield',
            name='donation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brownfield',
            name='status',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'in progress'), (2, 'to be approved'), (3, 'deactivated'), (4, 'private')], default=1, help_text='Status'),
        ),
        migrations.AddField(
            model_name='developmentpark',
            name='donation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='developmentpark',
            name='status',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'in progress'), (2, 'to be approved'), (3, 'deactivated'), (4, 'private')], default=1, help_text='Status'),
        ),
        migrations.AddField(
            model_name='greenfield',
            name='donation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenfield',
            name='status',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'in progress'), (2, 'to be approved'), (3, 'deactivated'), (4, 'private')], default=1, help_text='Status'),
        ),
        migrations.AddField(
            model_name='industrialareal',
            name='donation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='industrialareal',
            name='status',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'in progress'), (2, 'to be approved'), (3, 'deactivated'), (4, 'private')], default=1, help_text='Status'),
        ),
        migrations.AddField(
            model_name='office',
            name='donation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='office',
            name='status',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'in progress'), (2, 'to be approved'), (3, 'deactivated'), (4, 'private')], default=1, help_text='Status'),
        ),
        migrations.AddField(
            model_name='scientificpark',
            name='donation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificpark',
            name='status',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'in progress'), (2, 'to be approved'), (3, 'deactivated'), (4, 'private')], default=1, help_text='Status'),
        ),
        migrations.AddField(
            model_name='developmentparkwastewatersevage',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkwastewaterrain',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkwastewaterindustrial',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparktelecommunication',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparktechnologicalwater',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkphoto',
            name='green_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparklocation',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkgenericnote',
            name='green_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkgas',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkelectricity',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkdrinkwater',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
        migrations.AddField(
            model_name='developmentparkattachment',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark'),
        ),
    ]
