# Generated by Django 2.0.5 on 2018-08-23 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cigeo', '0003_airport_publictransportstop_railwaystation'),
        ('addresses', '0001_initial'),
        ('entrepreneurial_property', '0006_industrialarealattachment_industrialarealdrinkwater_industrialarealelectricity_industrialarealgas_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('attachment', models.FileField(help_text='Attachment file', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeDrinkWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeElectricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeGas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeGenericNote',
            fields=[
                ('genericnote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cigeo.GenericNote')),
            ],
            bases=('cigeo.genericnote',),
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Body, linie, polygony', null=True, srid=4326, verbose_name='Geometrie')),
                ('highway_distance', models.FloatField(default=-1)),
                ('airport_distance', models.FloatField(default=-1)),
                ('public_transport_distance', models.FloatField(default=-1)),
                ('railway_distance', models.FloatField(default=-1)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='addresses.Address', verbose_name='Adresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('image', models.ImageField(help_text='Image file', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeTechnologicalWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeTelecommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('technology', models.CharField(blank=True, choices=[('optic', 'Optic'), ('metalic', 'Metalic'), ('wifi', 'WIFI'), ('cell', 'Cellular')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeWasteWaterIndustrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeWasteWaterRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeWasteWaterSevage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='office',
            name='access_road',
        ),
        migrations.RemoveField(
            model_name='office',
            name='railway_siding',
        ),
        migrations.RemoveField(
            model_name='office',
            name='total_area',
        ),
        migrations.AddField(
            model_name='officewastewatersevage',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officewastewaterrain',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officewastewaterindustrial',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officetelecommunication',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officetechnologicalwater',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officephoto',
            name='green_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officegenericnote',
            name='green_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officegas',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officeelectricity',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officedrinkwater',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
        migrations.AddField(
            model_name='officeattachment',
            name='green_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office'),
        ),
    ]
