# Generated by Django 2.0.5 on 2018-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0009_brownfield_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brownfield',
            name='smallest_divide_size',
            field=models.IntegerField(blank=True, help_text='Smallest size of divided unit <code>m<sup>2</sup>]</code>', null=True),
        ),
        migrations.AlterField(
            model_name='developmentpark',
            name='smallest_divide_size',
            field=models.IntegerField(blank=True, help_text='Smallest size of divided unit <code>m<sup>2</sup>]</code>', null=True),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='smallest_divide_size',
            field=models.IntegerField(blank=True, help_text='Smallest size of divided unit <code>m<sup>2</sup>]</code>', null=True),
        ),
        migrations.AlterField(
            model_name='industrialareal',
            name='smallest_divide_size',
            field=models.IntegerField(blank=True, help_text='Smallest size of divided unit <code>m<sup>2</sup>]</code>', null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='smallest_divide_size',
            field=models.IntegerField(blank=True, help_text='Smallest size of divided unit <code>m<sup>2</sup>]</code>', null=True),
        ),
        migrations.AlterField(
            model_name='scientificpark',
            name='smallest_divide_size',
            field=models.IntegerField(blank=True, help_text='Smallest size of divided unit <code>m<sup>2</sup>]</code>', null=True),
        ),
    ]
