# Generated by Django 2.0.5 on 2018-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0010_auto_20180823_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentpark',
            name='available_since',
            field=models.DateField(blank=True, help_text='Available since', null=True),
        ),
        migrations.AlterField(
            model_name='greenfield',
            name='available_since',
            field=models.DateField(blank=True, help_text='Available since', null=True),
        ),
        migrations.AlterField(
            model_name='industrialareal',
            name='available_since',
            field=models.DateField(blank=True, help_text='Available since', null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='available_since',
            field=models.DateField(blank=True, help_text='Available since', null=True),
        ),
        migrations.AlterField(
            model_name='scientificpark',
            name='available_since',
            field=models.DateField(blank=True, help_text='Available since', null=True),
        ),
    ]
