# Generated by Django 2.0.5 on 2018-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0011_auto_20180823_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenfield',
            name='af_removal_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
