# Generated by Django 2.0.5 on 2018-09-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0012_auto_20180823_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrownfieldWasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('cleaning_type', models.CharField(choices=[(0, 'Sevage'), (1, 'Rain'), (2, 'Industry')], max_length=10, verbose_name='Typ čistírny')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
                ('green_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Brownfield')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentParkWasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('cleaning_type', models.CharField(choices=[(0, 'Sevage'), (1, 'Rain'), (2, 'Industry')], max_length=10, verbose_name='Typ čistírny')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
                ('green_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.DevelopmentPark')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreenFieldWasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('cleaning_type', models.CharField(choices=[(0, 'Sevage'), (1, 'Rain'), (2, 'Industry')], max_length=10, verbose_name='Typ čistírny')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
                ('green_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.GreenField')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrialArealWasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('cleaning_type', models.CharField(choices=[(0, 'Sevage'), (1, 'Rain'), (2, 'Industry')], max_length=10, verbose_name='Typ čistírny')),
                ('diameter', models.IntegerField(blank=True, help_text='Velikost přípojky <code>[mm]</code>', verbose_name='Průměr')),
                ('capacity', models.IntegerField(blank=True, help_text='Kapacita přípojky <code>[m<sup>3</sup>/d]</code>', verbose_name='Kapacita přípojky')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
                ('green_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.IndustrialAreal')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeWasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('cleaning_type', models.CharField(choices=[(0, 'Sevage'), (1, 'Rain'), (2, 'Industry')], max_length=10, verbose_name='Typ čistírny')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
                ('green_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.Office')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScientificParkWasteWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='Dinstance to object <code>[m]</code>', verbose_name='Distnace')),
                ('note', models.TextField(blank=True, help_text='Note', verbose_name='Note')),
                ('cleaning_type', models.CharField(choices=[(0, 'Sevage'), (1, 'Rain'), (2, 'Industry')], max_length=10, verbose_name='Typ čistírny')),
                ('sewage_plant_name', models.TextField(blank=True, help_text='Name and address')),
                ('sewage_plant_technology', models.CharField(blank=True, max_length=10)),
                ('absorbtion', models.CharField(blank=True, help_text='River name, where the water will be absorbed', max_length=64)),
                ('green_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurial_property.ScientificPark')),
            ],
            options={
                'verbose_name': 'Kanalizace',
                'verbose_name_plural': 'Kanalizace',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='brownfieldwastewaterindustrial',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='brownfieldwastewaterrain',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='brownfieldwastewatersevage',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='developmentparkwastewaterindustrial',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='developmentparkwastewaterrain',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='developmentparkwastewatersevage',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='greenfieldwastewaterindustrial',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='greenfieldwastewaterrain',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='greenfieldwastewatersevage',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='industrialarealwastewaterindustrial',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='industrialarealwastewaterrain',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='industrialarealwastewatersevage',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='officewastewaterindustrial',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='officewastewaterrain',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='officewastewatersevage',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='scientificparkwastewaterindustrial',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='scientificparkwastewaterrain',
            name='green_field',
        ),
        migrations.RemoveField(
            model_name='scientificparkwastewatersevage',
            name='green_field',
        ),
        migrations.DeleteModel(
            name='BrownfieldWasteWaterIndustrial',
        ),
        migrations.DeleteModel(
            name='BrownfieldWasteWaterRain',
        ),
        migrations.DeleteModel(
            name='BrownfieldWasteWaterSevage',
        ),
        migrations.DeleteModel(
            name='DevelopmentParkWasteWaterIndustrial',
        ),
        migrations.DeleteModel(
            name='DevelopmentParkWasteWaterRain',
        ),
        migrations.DeleteModel(
            name='DevelopmentParkWasteWaterSevage',
        ),
        migrations.DeleteModel(
            name='GreenFieldWasteWaterIndustrial',
        ),
        migrations.DeleteModel(
            name='GreenFieldWasteWaterRain',
        ),
        migrations.DeleteModel(
            name='GreenFieldWasteWaterSevage',
        ),
        migrations.DeleteModel(
            name='IndustrialArealWasteWaterIndustrial',
        ),
        migrations.DeleteModel(
            name='IndustrialArealWasteWaterRain',
        ),
        migrations.DeleteModel(
            name='IndustrialArealWasteWaterSevage',
        ),
        migrations.DeleteModel(
            name='OfficeWasteWaterIndustrial',
        ),
        migrations.DeleteModel(
            name='OfficeWasteWaterRain',
        ),
        migrations.DeleteModel(
            name='OfficeWasteWaterSevage',
        ),
        migrations.DeleteModel(
            name='ScientificParkWasteWaterIndustrial',
        ),
        migrations.DeleteModel(
            name='ScientificParkWasteWaterRain',
        ),
        migrations.DeleteModel(
            name='ScientificParkWasteWaterSevage',
        ),
    ]
