# Generated by Django 2.0.5 on 2018-09-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0013_auto_20180905_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brownfieldwastewater',
            old_name='sewage_plant_name',
            new_name='sevage_plant_name',
        ),
        migrations.RenameField(
            model_name='brownfieldwastewater',
            old_name='sewage_plant_technology',
            new_name='sevage_plant_technology',
        ),
        migrations.RenameField(
            model_name='developmentparkwastewater',
            old_name='sewage_plant_name',
            new_name='sevage_plant_name',
        ),
        migrations.RenameField(
            model_name='developmentparkwastewater',
            old_name='sewage_plant_technology',
            new_name='sevage_plant_technology',
        ),
        migrations.RenameField(
            model_name='greenfieldwastewater',
            old_name='sewage_plant_name',
            new_name='sevage_plant_name',
        ),
        migrations.RenameField(
            model_name='greenfieldwastewater',
            old_name='sewage_plant_technology',
            new_name='sevage_plant_technology',
        ),
        migrations.RenameField(
            model_name='industrialarealwastewater',
            old_name='sewage_plant_name',
            new_name='sevage_plant_name',
        ),
        migrations.RenameField(
            model_name='industrialarealwastewater',
            old_name='sewage_plant_technology',
            new_name='sevage_plant_technology',
        ),
        migrations.RenameField(
            model_name='officewastewater',
            old_name='sewage_plant_name',
            new_name='sevage_plant_name',
        ),
        migrations.RenameField(
            model_name='officewastewater',
            old_name='sewage_plant_technology',
            new_name='sevage_plant_technology',
        ),
        migrations.RenameField(
            model_name='scientificparkwastewater',
            old_name='sewage_plant_name',
            new_name='sevage_plant_name',
        ),
        migrations.RenameField(
            model_name='scientificparkwastewater',
            old_name='sewage_plant_technology',
            new_name='sevage_plant_technology',
        ),
    ]
