# Generated by Django 2.0.5 on 2018-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurial_property', '0014_auto_20180905_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brownfieldwastewater',
            options={'verbose_name': 'Odpadní voda', 'verbose_name_plural': 'Odpadní vody'},
        ),
        migrations.AlterModelOptions(
            name='developmentparkwastewater',
            options={'verbose_name': 'Odpadní voda', 'verbose_name_plural': 'Odpadní vody'},
        ),
        migrations.AlterModelOptions(
            name='greenfieldwastewater',
            options={'verbose_name': 'Odpadní voda', 'verbose_name_plural': 'Odpadní vody'},
        ),
        migrations.AlterModelOptions(
            name='industrialarealwastewater',
            options={'verbose_name': 'Odpadní voda', 'verbose_name_plural': 'Odpadní vody'},
        ),
        migrations.AlterModelOptions(
            name='officewastewater',
            options={'verbose_name': 'Odpadní voda', 'verbose_name_plural': 'Odpadní vody'},
        ),
        migrations.AlterModelOptions(
            name='scientificparkwastewater',
            options={'verbose_name': 'Odpadní voda', 'verbose_name_plural': 'Odpadní vody'},
        ),
        migrations.AddField(
            model_name='brownfield',
            name='uuid',
            field=models.CharField(default='6cfe1b7c-0699-466a-99c0-04523b11b3ea', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developmentpark',
            name='uuid',
            field=models.CharField(default='6cfe1b7c-0699-466a-99c0-04523b11b3ea', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenfield',
            name='uuid',
            field=models.CharField(default='6cfe1b7c-0699-466a-99c0-04523b11b3ea', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrialareal',
            name='uuid',
            field=models.CharField(default='6cfe1b7c-0699-466a-99c0-04523b11b3ea', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='uuid',
            field=models.CharField(default='6cfe1b7c-0699-466a-99c0-04523b11b3ea', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificpark',
            name='uuid',
            field=models.CharField(default='6cfe1b7c-0699-466a-99c0-04523b11b3ea', max_length=36),
            preserve_default=False,
        ),
    ]
