# Generated by Django 2.2.3 on 2019-10-29 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('name_en', models.CharField(blank=True, help_text='Name (english)', max_length=200)),
                ('url', models.URLField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai.Form')),
            ],
        ),
    ]
