# Generated by Django 2.2.3 on 2019-10-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_ai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='sector',
            new_name='form',
        ),
    ]
