# Generated by Django 3.1.1 on 2021-02-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0003_address_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('director', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.address')),
            ],
        ),
    ]
